# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: PRUG
email: your-email@example.com
description: Poznań Ruby User Group
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# google_analytics:

social_media:
  discord: https://discord.gg/JxM8GNsUF9
  facebook: https://www.facebook.com/rubypoznan
  meetup: https://www.meetup.com/PoznanRUG
  github: https://github.com/prug

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-postcss-v2

postcss:
  cache: false

sass:
  sass_dir: _sass/
  load_paths:
    - ./node_modules/
